#!/usr/bin/env bash

echo "Replacing ~/.wezterm.lua with symlink/copy."
ln -sf "$PWD/wezterm.lua" ~/.wezterm.lua

if [[ $OSTYPE =~ ^darwin ]]; then
	echo "Installing fontconfig."
	brew install fontconfig
fi

if [[ "$OSTYPE" = "msys" ]]; then
	echo "Installing 'Ubuntu Mono' (NerdFont) fonts."
	# shellcheck disable=SC2016
	powershell -Command '& ([scriptblock]::Create((iwr "https://to.loredo.me/Install-NerdFont.ps1"))) -Name "ubuntu-mono" -Confirm:$false
'
else
	if [[ ! -e ~/.local/share/fonts/HackNerdFont-Regular.ttf ]]; then
		echo "Installing 'HackNerdFont-Regular.ttf' fonts."
		mkdir -p ~/.local/share/fonts
		unzip Hack.zip -d ~/.local/share/fonts/
		fc-cache -fv
	fi
fi
