#!/bin/sh

wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | \
    sudo tee /usr/share/keyrings/packages.microsoft.gpg > /dev/null

echo "deb [signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | \
    sudo tee /etc/apt/sources.list.d/vscode.list

sudo apt update
sudo apt install -y code

code --version

echo "Installing extensions from ~/.config/Code/User/extensions.txt"
cat ~/.config/Code/User/extensions.txt | xargs -n1 code --install-extension